" packages
set nocompatible              " be iMproved, required
set hidden
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'syntastic'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-unimpaired'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'phpcomplete-extended'
Plugin 'vimwiki/vimwiki'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'xoria256.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" leader key
let mapleader = " "
let g:mapleader = " "

" mappings for unite
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q!<cr>
nnoremap <leader>f :Unite -start-insert buffer<cr>
nnoremap <leader>F :Unite -start-insert file_rec/async<cr>

" mappings for ultisnips
let g:UltiSnipsExpandTrigger="<c-\\>"

" configure for vimwiki
let g:vimwiki_list = [
 \{"path": "~/vimwiki/", 
 \ "path_html": "~/wiki/",
 \ "syntax": "markdown", 
 \ "ext": ".vk",
 \ "auto_export": 0}
 \]

" general settings
set tabstop=4
set shiftwidth=4
set softtabstop=0 expandtab

" color config
colorscheme xoria256
