//
// This file is generated by parsec-rdl-gen (development version)
// WILL NOT be auto-generated if file has already existed.
//
package com.example;

import com.example.parsec_generated.ResourceContext;
import com.example.parsec_generated.SampleHandler;
import com.example.parsec_generated.User;
import com.example.services.SampleService;
import org.asynchttpclient.AsyncHttpClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * SampleHandlerImpl is interface implementation that implement SampleHandler interface.
 */
public class SampleHandlerImpl implements SampleHandler {
    private static Logger LOGGER = LoggerFactory.getLogger(SampleHandlerImpl.class);

    private final AsyncHttpClient asyncHttpClient;
    private final SampleService sampleService;

    @Inject
    SampleHandlerImpl(AsyncHttpClient asyncHttpClient, SampleService sampleService) {
        this.asyncHttpClient = asyncHttpClient;
        this.sampleService = sampleService;
    }

    @Override
    public User postUser(ResourceContext context, User user) {
        return null;
    }

    @Override
    public User getUser(ResourceContext context, Integer id) {
        sampleService.fetchAllService();
        return new User();
    }

    @Override
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response) {
        return new DefaultResourceContext(request, response);
    }
}
