#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

# PID=$(ps -ef | grep spring-boot:run | grep -v grep | awk '{ print $2 }')
PID=$(ps -ef | grep "dart" | grep -v grep | awk '{ print $2 }')

if [ -z "$PID" ]
then
  client_result "Application is already stopped"
else
  kill $PID
fi